baseURL: 'https://blog.ddavo.me/'
defaultContentLanguage: en
languages:
  en:
    weight: 1
  es:
    weight: 2
    params:
      description: >
        Blog de desarrollador de David Davó, en el que encontrarás notas sobre mis proyectos (entre otras cosas)
title: >
  David Davó's dev log
copyright: 'David Davó (c) 2021'
theme: "PaperMod"
paginate: 5
markup:
  goldmark:
    extensions:
      strikethrough: true
      table: true
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
params:
  ShowShareButtons: true
  description: >
    David Davó's dev log where you'll find notes about my projects, among other things
  author: David Davó
  keywords: [Blog, Portfolio, Devlog]
  DateFormat: "2006-01-02"
  comments: true
  socialIcons:
    - name: kofi
      url: 'https://ko-fi.com/ddavo'
    - name: email
      url: 'david@ddavo.me'
    - name: github
      url: 'https://github.com/daviddavo'
    - name: gitlab
      url: 'https://gitlab.com/daviddavo'
    - name: linkedin
      url: 'https://www.linkedin.com/in/ddavo/'