baseURL: 'https://blog.ddavo.me/'
languageCode: 'en-uk'
title: >
  David Dav贸's dev log
copyright: 'David Dav贸 (c) 2021'
theme: "PaperMod"
paginate: 5
params:
  ShowShareButtons: true
  description: >
    David Dav贸's dev log where you'll find notes about my projects, among other things
  author: David Dav贸
  keywords: [Blog, Portfolio, Devlog]
  socialIcons:
    - name: kofi
      url: 'https://ko-fi.com/ddavo'
    - name: email
      url: 'david@ddavo.me'
    - name: github
      url: 'https://github.com/daviddavo'
    - name: gitlab
      url: 'https://gitlab.com/daviddavo'
    - name: linkedin
      url: 'https://www.linkedin.com/in/ddavo/'