name: Deploy to cloudflare pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-drafts:
    strategy:
      matrix:
        version: ['0.118.0', '0.119.0', '0.120.0', '0.121.0', '0.122.0', '0.123.0', '0.124.0', '0.125.0', '0.126.0', '0.126.1']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0   # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.version }}
          extended: true

      - name: Build
        run: hugo -EDF --environment drafts --minify

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "blog-ddavo"
          directory: "public"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: drafts-${{ matrix.version }}