name: Update data viz
on:
  schedule:
    # Everyday at 2:42
    # TODO: Run every hour but modify updateAllData.sh
    # to specify when each script should run / upload
    - cron: '42 2 * * *'
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      # No need for submodules in this case
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: auto
      - name: Update and upload all data
        run: ./updateAllData.sh --upload
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_BUCKET: blog-ddavo
